version: '3'
services:
  mysql:
    image: 'mysql:8.0.21'
    ports:
      - '3306:3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser

  redis:
    image: 'redis:6.0.6'
    ports:
      - '6379:6379'