version: '3'
services:
  mysql:
    image: 'mysql:8.0.21'
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: 'redis:6.0.6'
    ports:
      - '6379:6379'

  api:
    image: 'alexandrealvino/nf_stn:latest'
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_DRIVER: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: nf_stn
      URL: 'mysql:3306'
      REDIS_DSN: 'redis:6379'
      ACCESS_SECRET: jdnfksdmfksd
      REFRESH_SECRET: mcmvmkmsdnfsdmfdsjf

