version: '3'
services:
  mysql:
    image: 'mysql:8.0.21'
    ports:
      - '3306:3306'
    volumes:
      - schema:/schema.sql
      - ./schema:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nf_stn
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
# Volumes
volumes:
  schema:
#  redis:
#    image: 'redis:6.0.6'
#    ports:
#      - '6379:6379'