// Code generated by MockGen. DO NOT EDIT.
// Source: db_queries.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	entities "nf_stn/entities"
	reflect "reflect"
)

// MockDataBase is a mock of DataBase interface
type MockDataBase struct {
	ctrl     *gomock.Controller
	recorder *MockDataBaseMockRecorder
}

// MockDataBaseMockRecorder is the mock recorder for MockDataBase
type MockDataBaseMockRecorder struct {
	mock *MockDataBase
}

// NewMockDataBase creates a new mock instance
func NewMockDataBase(ctrl *gomock.Controller) *MockDataBase {
	mock := &MockDataBase{ctrl: ctrl}
	mock.recorder = &MockDataBaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDataBase) EXPECT() *MockDataBaseMockRecorder {
	return m.recorder
}

// Init mocks base method
func (m *MockDataBase) Init() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Init")
}

// Init indicates an expected call of Init
func (mr *MockDataBaseMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockDataBase)(nil).Init))
}

// GetInvoices mocks base method
func (m *MockDataBase) GetInvoices(params entities.SearchParameters) ([]entities.Invoice, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoices", params)
	ret0, _ := ret[0].([]entities.Invoice)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetInvoices indicates an expected call of GetInvoices
func (mr *MockDataBaseMockRecorder) GetInvoices(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoices", reflect.TypeOf((*MockDataBase)(nil).GetInvoices), params)
}

// GetInvoiceByDocument mocks base method
func (m *MockDataBase) GetInvoiceByDocument(document string) (entities.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceByDocument", document)
	ret0, _ := ret[0].(entities.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceByDocument indicates an expected call of GetInvoiceByDocument
func (mr *MockDataBaseMockRecorder) GetInvoiceByDocument(document interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceByDocument", reflect.TypeOf((*MockDataBase)(nil).GetInvoiceByDocument), document)
}

// GetUser mocks base method
func (m *MockDataBase) GetUser(username string) (int, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", username)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetUser indicates an expected call of GetUser
func (mr *MockDataBaseMockRecorder) GetUser(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockDataBase)(nil).GetUser), username)
}

// GetInvoiceByID mocks base method
func (m *MockDataBase) GetInvoiceByID(id int) (entities.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceByID", id)
	ret0, _ := ret[0].(entities.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceByID indicates an expected call of GetInvoiceByID
func (mr *MockDataBaseMockRecorder) GetInvoiceByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceByID", reflect.TypeOf((*MockDataBase)(nil).GetInvoiceByID), id)
}

// InsertInvoice mocks base method
func (m *MockDataBase) InsertInvoice(invoice entities.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertInvoice", invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertInvoice indicates an expected call of InsertInvoice
func (mr *MockDataBaseMockRecorder) InsertInvoice(invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertInvoice", reflect.TypeOf((*MockDataBase)(nil).InsertInvoice), invoice)
}

// DeleteInvoice mocks base method
func (m *MockDataBase) DeleteInvoice(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvoice", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvoice indicates an expected call of DeleteInvoice
func (mr *MockDataBaseMockRecorder) DeleteInvoice(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvoice", reflect.TypeOf((*MockDataBase)(nil).DeleteInvoice), id)
}

// UpdateInvoice mocks base method
func (m *MockDataBase) UpdateInvoice(invoice entities.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInvoice", invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInvoice indicates an expected call of UpdateInvoice
func (mr *MockDataBaseMockRecorder) UpdateInvoice(invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInvoice", reflect.TypeOf((*MockDataBase)(nil).UpdateInvoice), invoice)
}

// PatchInvoice mocks base method
func (m *MockDataBase) PatchInvoice(invoice entities.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchInvoice", invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchInvoice indicates an expected call of PatchInvoice
func (mr *MockDataBaseMockRecorder) PatchInvoice(invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchInvoice", reflect.TypeOf((*MockDataBase)(nil).PatchInvoice), invoice)
}

// InvoiceExists mocks base method
func (m *MockDataBase) InvoiceExists(document string) (entities.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvoiceExists", document)
	ret0, _ := ret[0].(entities.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvoiceExists indicates an expected call of InvoiceExists
func (mr *MockDataBaseMockRecorder) InvoiceExists(document interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvoiceExists", reflect.TypeOf((*MockDataBase)(nil).InvoiceExists), document)
}

// NewMockDbClient mocks
func NewMockDbClient(ctrl *gomock.Controller) *MockDataBase {
	mock := &MockDataBase{ctrl: ctrl}
	mock.recorder = &MockDataBaseMockRecorder{mock}
	return mock
}